#!/usr/bin/env python3

import re
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

'''
create a list of file paths of the outputs generated by `translate_ddG.py`
The files output from that script should look like this:

`output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_model/out_energies.csv`:
DesignNum,PeptideSequence,bound_dG,unbound_dG,ddG
0,TGGRLGNRSGTQALGK,-993.2077853755554,-967.6941463143296,-25.51363906122583

If there were rosetta-designed sequences, they appear in the same csv as more rows. Likely this plotting script will only ever want the first row.

Old structure of these files had only two columns. 
`comdn230-c16-13_model_dgoutput/out_energies.csv`:
struct,energy
/projects/parisahlab/wesg/af3_data/20250920_AF3_output/comdn230-c16-13/comdn230-c16-13_model.pdb_RAW,579.584659270761
/projects/parisahlab/wesg/af3_data/20250920_AF3_output/comdn230-c16-13/comdn230-c16-13_model.pdb_relaxed,-636.2237708726736
/projects/parisahlab/wesg/af3_data/20250920_AF3_output/comdn230-c16-13/comdn230-c16-13_model.pdb_translated,-620.6306885020979
/projects/parisahlab/wesg/af3_data/20250920_AF3_output/comdn230-c16-13/comdn230-c16-13_model.pdb_diff,-15.593082370575758
'''

# file_list must be a list of lists. Interior lists should contain all files with data to average.
file_list = [
        ["output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-13_seed-1_sample-4_model/out_energies.csv"],

        ["output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-14_seed-1_sample-4_model/out_energies.csv"],

        ["output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-15_seed-1_sample-4_model/out_energies.csv"],

        ["output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-16_seed-1_sample-4_model/out_energies.csv"],

        ["output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-17_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184439_ddGout_sepmcsp16-17_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184453_ddGout_sepmcsp16-17_seed-1_sample-4_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184454_ddGout_sepmcsp16-17_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184454_ddGout_sepmcsp16-17_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184454_ddGout_sepmcsp16-17_seed-1_sample-3_model/out_energies.csv"],

        ["output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16-18_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184454_ddGout_sepmcsp16-18_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16-18_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16-18_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16-18_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16-18_seed-1_sample-4_model/out_energies.csv"],
        
        ["output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184455_ddGout_sepmcsp16_seed-1_sample-0_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184454_ddGout_sepmcsp16_seed-1_sample-1_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184524_ddGout_sepmcsp16_seed-1_sample-2_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184525_ddGout_sepmcsp16_seed-1_sample-3_model/out_energies.csv",
         "output/20251005_deltaGoutput/20251005-184525_ddGout_sepmcsp16_seed-1_sample-4_model/out_energies.csv"]]
            

def collect_ddGs_to_file(file_list: list):
    with open("deltadeltaGs.tsv", 'w') as fout: 
        fout.write("structure\tddG\n")
        for files in file_list: 
            sum = 0
            numfiles = 0
            # name = files[0].split("_fixed_dgoutput")[0]
            name = re.search(r'_ddGout_' + r'(.*?)' + r'_model.', files[0], re.DOTALL).group(0)
            
            name = re.sub(r"_ddGout_", '', name)
            name = re.sub(r"_model.$", '', name)
            print(files[0])
            print(name)
            ddG_list = []
            for file in files:
                df = pd.read_csv(file)
                ddG_list.append(df.iloc[0, 4])

            print(ddG_list)
            ddG_mean = np.mean(ddG_list) / len(ddG_list) 
            # change this!
            fout.write(f"{name}\t{ddG_mean}\n")
            # to the below
            # fout.write(f"{name}\t{ddG_list}\n")

def plot_dGs(filename: str): 
    plt.clf()
    df = pd.read_csv(filename, sep='\t')
    fig, ax = plt.subplots()
    labels = df['structure']
    ax.bar(range(len(labels)),df['ddG'])

    ax.set_xlabel('Variant')
    ax.set_xticks(range(len(labels)), labels, rotation='vertical')
    ax.set_ylabel('ddG')
    ax.set_title('Delta Delta G: CSP variants')
    plt.subplots_adjust(bottom=0.4) 
    plt.savefig("ddG_figure.pdf", format="pdf")

if __name__ == "__main__":
    collect_ddGs_to_file(file_list)
    plot_dGs("deltadeltaGs.tsv")
